### ISSUE TITLE
No such file or directory: '/Users/$USER/go/bin/puppy': '/Users/$USER/go/bin/puppy'

### ISSUE THREAD

**Issue by publicarray** [roglew/guppy-proxy#1]
https://github.com/roglew/guppy-proxy/blob/3b20c16b0859261ed9c659380ec418e8259f32b6/install.sh#L117

I reckon this should be

```sh
 require "$GO" build -o "$GOPATH"/bin/puppy $BUILDFLAGS "puppy/cmd/main"; 
```

**Comment by roglew** [comment]
Hey! Thanks for the info. I'll be getting this fixed this weekend.

**Comment by roglew** [comment]
Done! This was fixed with https://github.com/roglew/guppy-proxy/commit/eead1e908f0855a1716dfe3618e45c137295dd2b

**Comment by publicarray** [comment]
Thanks 👍

**Comment by publicarray** [comment]
But why not install the binary into the $GOPATH like everything else?
